apiVersion: v1
kind: Service
metadata:
  labels:
    app: ngnix
  name: ngnix
  namespace: default
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: ngnix
  type: NodePort
