apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ngnix
  name: ngnix
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ngnix
  template:
    metadata:
      labels:
        app: ngnix
    spec:
      containers:
      - image: ngnix
        name: ngnix
